package report

import (
	"fmt"
	"html"
	"os"
	"strings"
	"time"

	"github.com/ojuschugh1/etch/internal/diff"
)

// GenerateHTML creates a self-contained HTML diff report.
func GenerateHTML(results []diff.DiffResult, outputPath string) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("creating report file: %w", err)
	}
	defer f.Close()

	totalDiffs := 0
	criticalCount := 0
	warningCount := 0
	infoCount := 0

	for _, r := range results {
		classified := diff.ClassifyDiffs(r.Fields)
		for _, c := range classified {
			totalDiffs++
			switch c.Severity {
			case diff.SeverityCritical:
				criticalCount++
			case diff.SeverityWarning:
				warningCount++
			case diff.SeverityInfo:
				infoCount++
			}
		}
	}

	fmt.Fprintf(f, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Etch Diff Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace; background: #0d1117; color: #c9d1d9; padding: 24px; }
  h1 { color: #f0f6fc; margin-bottom: 8px; font-size: 24px; }
  .meta { color: #8b949e; margin-bottom: 24px; font-size: 14px; }
  .summary { display: flex; gap: 16px; margin-bottom: 24px; }
  .stat { padding: 12px 20px; border-radius: 8px; font-size: 14px; }
  .stat-critical { background: #3d1117; color: #f85149; border: 1px solid #f8514933; }
  .stat-warning { background: #2d1d00; color: #d29922; border: 1px solid #d2992233; }
  .stat-info { background: #0d1d2d; color: #58a6ff; border: 1px solid #58a6ff33; }
  .stat-match { background: #0d2d1d; color: #3fb950; border: 1px solid #3fb95033; }
  .endpoint { background: #161b22; border: 1px solid #30363d; border-radius: 8px; margin-bottom: 16px; overflow: hidden; }
  .endpoint-header { padding: 12px 16px; background: #21262d; font-weight: 600; font-size: 14px; }
  .diff-row { padding: 8px 16px; border-top: 1px solid #21262d; font-size: 13px; display: flex; align-items: baseline; gap: 8px; }
  .severity-critical { color: #f85149; }
  .severity-warning { color: #d29922; }
  .severity-info { color: #8b949e; }
  .path { color: #79c0ff; min-width: 200px; }
  .expected { color: #f85149; text-decoration: line-through; }
  .actual { color: #3fb950; }
  .arrow { color: #8b949e; }
  .reason { color: #8b949e; font-size: 12px; margin-left: auto; }
  .footer { margin-top: 24px; color: #484f58; font-size: 12px; text-align: center; }
</style>
</head>
<body>
<h1>Etch Diff Report</h1>
<p class="meta">Generated %s</p>
<div class="summary">
`, html.EscapeString(time.Now().Format("2006-01-02 15:04:05")))

	if criticalCount > 0 {
		fmt.Fprintf(f, `  <div class="stat stat-critical">%d critical</div>`+"\n", criticalCount)
	}
	if warningCount > 0 {
		fmt.Fprintf(f, `  <div class="stat stat-warning">%d warning</div>`+"\n", warningCount)
	}
	if infoCount > 0 {
		fmt.Fprintf(f, `  <div class="stat stat-info">%d info</div>`+"\n", infoCount)
	}
	matched := len(results) == 0
	if matched {
		fmt.Fprintf(f, `  <div class="stat stat-match">All responses match</div>`+"\n")
	}

	fmt.Fprintf(f, "</div>\n")

	for _, r := range results {
		if r.Matched {
			continue
		}
		classified := diff.ClassifyDiffs(r.Fields)

		fmt.Fprintf(f, `<div class="endpoint">`+"\n")
		fmt.Fprintf(f, `  <div class="endpoint-header">✗ %s</div>`+"\n", html.EscapeString(r.URL))

		for _, c := range classified {
			sevClass := "severity-warning"
			sym := "!"
			switch c.Severity {
			case diff.SeverityCritical:
				sevClass = "severity-critical"
				sym = "✗"
			case diff.SeverityInfo:
				sevClass = "severity-info"
				sym = "~"
			}

			fmt.Fprintf(f, `  <div class="diff-row">`+"\n")
			fmt.Fprintf(f, `    <span class="%s">%s</span>`+"\n", sevClass, sym)
			fmt.Fprintf(f, `    <span class="path">%s</span>`+"\n", html.EscapeString(c.Path))

			if c.Expected == "" {
				fmt.Fprintf(f, `    <span class="actual">(added) %s</span>`+"\n", html.EscapeString(c.Actual))
			} else if c.Actual == "" {
				fmt.Fprintf(f, `    <span class="expected">%s (removed)</span>`+"\n", html.EscapeString(c.Expected))
			} else {
				fmt.Fprintf(f, `    <span class="expected">%s</span>`+"\n", html.EscapeString(c.Expected))
				fmt.Fprintf(f, `    <span class="arrow">&rarr;</span>`+"\n")
				fmt.Fprintf(f, `    <span class="actual">%s</span>`+"\n", html.EscapeString(c.Actual))
			}

			fmt.Fprintf(f, `    <span class="reason">[%s]</span>`+"\n", html.EscapeString(c.Reason))
			fmt.Fprintf(f, `  </div>`+"\n")
		}

		fmt.Fprintf(f, `</div>`+"\n")
	}

	fmt.Fprintf(f, `<div class="footer">Generated by <a href="https://github.com/ojuschugh1/etch" style="color:#58a6ff">etch</a> - API change detection</div>`+"\n")
	fmt.Fprintf(f, "</body>\n</html>\n")

	return nil
}

// FormatSummary returns a one-line summary for terminal output.
func FormatSummary(results []diff.DiffResult) string {
	if len(results) == 0 {
		return "No diffs to report."
	}
	endpoints := 0
	fields := 0
	for _, r := range results {
		if !r.Matched {
			endpoints++
			fields += len(r.Fields)
		}
	}
	return fmt.Sprintf("%d endpoint(s) with %d field change(s)", endpoints, fields)
}

// CollectDiffs gathers all DiffResults from a test summary's Diffs slice.
func CollectDiffs(rawDiffs []interface{}) []diff.DiffResult {
	var results []diff.DiffResult
	for _, raw := range rawDiffs {
		if d, ok := raw.(diff.DiffResult); ok && !d.Matched {
			results = append(results, d)
		}
	}
	return results
}

// DefaultPath returns the default output path for HTML reports.
func DefaultPath() string {
	return "etch-report.html"
}

// WriteReport is a convenience function that generates the HTML report
// and prints a message about where it was saved.
func WriteReport(results []diff.DiffResult, path string) error {
	if err := GenerateHTML(results, path); err != nil {
		return err
	}
	summary := FormatSummary(results)
	fmt.Printf("Report saved to %s (%s)\n", path, summary)
	return nil
}

// Needed for the strings import
var _ = strings.Contains
